---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

---
spring:
  profiles: subject
words: I,You,He,She,It,We,You,They

---
spring:
  profiles: verb
words: ran,knew,had,saw,bought

---
spring:
  profiles: article
words: a,the

---
spring:
  profiles: adjective
words: presumable,deliquescent,skeptical,usual,unusual

---
spring:
  profiles: noun
words: ship,paper,pol,chair,bag,division,woodchuck
